// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxpkcxpcbqkzkepzmvej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54cGtjeHBjYnFremtlcHptdmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODQ0ODUsImV4cCI6MjA2OTI2MDQ4NX0.ZoZa79gumrW_EvXUR1shgZHOQDEFsmJu71StzukLS5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});